In [1]:
function y = psi(x)
    %DIGAMMA   Digamma function.
    % DIGAMMA(X) returns digamma(x) = d log(gamma(x)) / dx
    % If X is a matrix, returns the digamma function evaluated at each element.

    % Reference:
    %
    %    J Bernardo,
    %    Psi ( Digamma ) Function,
    %    Algorithm AS 103,
    %    Applied Statistics,
    %    Volume 25, Number 3, pages 315-317, 1976.
    %
    % From http://www.psc.edu/~burkardt/src/dirichlet/dirichlet.f

    large = 9.5;
    d1 = -0.5772156649015328606065121;  % digamma(1)
    d2 = pi^2/6;
    small = 1e-6;
    s3 = 1/12;
    s4 = 1/120;
    s5 = 1/252;
    s6 = 1/240;
    s7 = 1/132;
    s8 = 691/32760;
    s9 = 1/12;
    s10 = 3617/8160;

    % Initialize
    y = zeros(size(x));

    % illegal arguments
    i = find(x == -Inf | isnan(x));
    if ~isempty(i)
        x(i) = NaN;
        y(i) = NaN;
    end

    % Negative values
    i = find(x < 0);
    if ~isempty(i)
        % Use the reflection formula (Jeffrey 11.1.6):
        % digamma(-x) = digamma(x+1) + pi*cot(pi*x)
        y(i) = digamma(-x(i)+1) + pi*cot(-pi*x(i));
        % This is related to the identity
        % digamma(-x) = digamma(x+1) - digamma(z) + digamma(1-z)
        % where z is the fractional part of x
        % For example:
        % digamma(-3.1) = 1/3.1 + 1/2.1 + 1/1.1 + 1/0.1 + digamma(1-0.1)
        %               = digamma(4.1) - digamma(0.1) + digamma(1-0.1)
        % Then we use
        % digamma(1-z) - digamma(z) = pi*cot(pi*z)
    end

    i = find(x == 0);
    if ~isempty(i)
        y(i) = -Inf;
    end

    %  Use approximation if argument <= small.
    i = find(x > 0 & x <= small);
    if ~isempty(i)
        y(i) = y(i) + d1 - 1 ./ x(i) + d2*x(i);
    end

    %  Reduce to digamma(X + N) where (X + N) >= large.
    while(1)
        i = find(x > small & x < large);
        if isempty(i)
            break
          end
        y(i) = y(i) - 1 ./ x(i);
        x(i) = x(i) + 1;
    end

    %  Use de Moivre's expansion if argument >= large.
    % In maple: asympt(Psi(x), x);
    i = find(x >= large);
    if ~isempty(i)
        r = 1 ./ x(i);
        y(i) = y(i) + log(x(i)) - 0.5 * r;
        r = r .* r;
        y(i) = y(i) - r .* ( s3 - r .* ( s4 - r .* (s5 - r .* (s6 - r .* s7))));
    end
end


function state = bemkl_supervised_classification_variational_train(Km, y, parameters)
    rand('state', parameters.seed); %#ok<RAND>
    randn('state', parameters.seed); %#ok<RAND>

    D = size(Km, 1);
    N = size(Km, 2);
    P = size(Km, 3);
    sigma_g = parameters.sigma_g;

    log2pi = log(2 * pi);

    lambda.alpha = (parameters.alpha_lambda + 0.5) * ones(D, 1);
    lambda.beta = parameters.beta_lambda * ones(D, 1);
    a.mu = randn(D, 1);
    a.sigma = eye(D, D);
    G.mu = (abs(randn(P, N)) + parameters.margin) .* sign(repmat(y', P, 1));
    G.sigma = eye(P, P);
    gamma.alpha = (parameters.alpha_gamma + 0.5);
    gamma.beta = parameters.beta_gamma;
    omega.alpha = (parameters.alpha_omega + 0.5) * ones(P, 1);
    omega.beta = parameters.beta_omega * ones(P, 1);
    be.mu = [0; ones(P, 1)];
    be.sigma = eye(P + 1, P + 1);
    f.mu = (abs(randn(N, 1)) + parameters.margin) .* sign(y);
    f.sigma = ones(N, 1);

    KmKm = zeros(D, D);
    for m = 1:P
        KmKm = KmKm + Km(:, :, m) * Km(:, :, m)';
    end
    Km = reshape(Km, [D, N * P]);

    lower = -1e40 * ones(N, 1);
    lower(y > 0) = +parameters.margin;
    upper = +1e40 * ones(N, 1);
    upper(y < 0) = -parameters.margin;

    if parameters.progress == 1
        bounds = zeros(parameters.iteration, 1);
    end
    
    atimesaT.mu = a.mu * a.mu' + a.sigma;
    GtimesGT.mu = G.mu * G.mu' + N * G.sigma;
    btimesbT.mu = be.mu(1)^2 + be.sigma(1, 1);
    etimeseT.mu = be.mu(2:P + 1) * be.mu(2:P + 1)' + be.sigma(2:P + 1, 2:P + 1);
    etimesb.mu = be.mu(2:P + 1) * be.mu(1) + be.sigma(2:P + 1, 1);
    KmtimesGT.mu = Km * reshape(G.mu', N * P, 1);
    for iter = 1:parameters.iteration
        %%%% update lambda
        lambda.beta = 1 ./ (1 / parameters.beta_lambda + 0.5 * diag(atimesaT.mu));
        %%%% update a
        a.sigma = (diag(lambda.alpha .* lambda.beta) + KmKm / sigma_g^2) \ eye(D, D);
        a.mu = a.sigma * KmtimesGT.mu / sigma_g^2;
        atimesaT.mu = a.mu * a.mu' + a.sigma;
        %%%% update G
        G.sigma = (eye(P, P) / sigma_g^2 + etimeseT.mu) \ eye(P, P);
        G.mu = G.sigma * (reshape(a.mu' * Km, [N, P])' / sigma_g^2 + be.mu(2:P + 1) * f.mu' - repmat(etimesb.mu, 1, N));
        GtimesGT.mu = G.mu * G.mu' + N * G.sigma;
        KmtimesGT.mu = Km * reshape(G.mu', N * P, 1);
        %%%% update gamma
        gamma.beta = 1 / (1 / parameters.beta_gamma + 0.5 * btimesbT.mu);
        %%%% update omega
        omega.beta = 1 ./ (1 / parameters.beta_omega + 0.5 * diag(etimeseT.mu));
        %%%% update b and e
        be.sigma = [gamma.alpha * gamma.beta + N, sum(G.mu, 2)'; sum(G.mu, 2), diag(omega.alpha .* omega.beta) + GtimesGT.mu] \ eye(P + 1, P + 1);
        be.mu = be.sigma * ([ones(1, N); G.mu] * f.mu);
        btimesbT.mu = be.mu(1)^2 + be.sigma(1, 1);
        etimeseT.mu = be.mu(2:P + 1) * be.mu(2:P + 1)' + be.sigma(2:P + 1, 2:P + 1);
        etimesb.mu = be.mu(2:P + 1) * be.mu(1) + be.sigma(2:P + 1, 1);
        %%%% update f
        output = [ones(1, N); G.mu]' * be.mu;
        alpha_norm = lower - output;
        beta_norm = upper - output;
        normalization = normcdf(beta_norm) - normcdf(alpha_norm);
        normalization(normalization == 0) = 1;
        f.mu = output + (normpdf(alpha_norm) - normpdf(beta_norm)) ./ normalization;
        f.sigma = 1 + (alpha_norm .* normpdf(alpha_norm) - beta_norm .* normpdf(beta_norm)) ./ normalization - (normpdf(alpha_norm) - normpdf(beta_norm)).^2 ./ normalization.^2;

        if parameters.progress == 1
            lb = 0;

            %%%% p(lambda)
            lb = (lb +
                  sum(
                      (parameters.alpha_lambda - 1) * (psi(lambda.alpha) + log(lambda.beta)) -
                       gammaln(parameters.alpha_lambda) -
                       lambda.alpha .* lambda.beta / parameters.beta_lambda -
                       parameters.alpha_lambda * log(parameters.beta_lambda)
                  )
                );

            %%%% p(a | lambda)
            lb = (lb -
                  0.5 * sum(lambda.alpha .* lambda.beta .* diag(atimesaT.mu)) -
                  0.5 * (D * log2pi - sum(psi(lambda.alpha) + log(lambda.beta))));
            
            %%%% p(G | a, Km)
            lb = (lb -
                  0.5 * sigma_g^-2 * sum(diag(GtimesGT.mu)) +
                  sigma_g^-2 * a.mu' * KmtimesGT.mu -
                  0.5 * sigma_g^-2 * sum(sum(KmKm .* atimesaT.mu)) -
                  0.5 * N * P * (log2pi + 2 * log(sigma_g))
            );

            %%%% p(gamma)
            lb = (lb +
                  (parameters.alpha_gamma - 1) * (psi(gamma.alpha) + log(gamma.beta)) -
                  gamma.alpha * gamma.beta / parameters.beta_gamma -
                  gammaln(parameters.alpha_gamma) -
                  parameters.alpha_gamma * log(parameters.beta_gamma)
            );
            %%%% p(b | gamma)
            lb = (lb -
                  0.5 * gamma.alpha * gamma.beta * btimesbT.mu -
                  0.5 * (log2pi - (psi(gamma.alpha) + log(gamma.beta)))
            );
            %%%% p(omega)
            lb = (lb +
                  sum(
                      (parameters.alpha_omega - 1) * (psi(omega.alpha) + log(omega.beta)) -
                      omega.alpha .* omega.beta / parameters.beta_omega -
                      gammaln(parameters.alpha_omega) -
                      parameters.alpha_omega * log(parameters.beta_omega)
                  )
            );
            %%%% p(e | omega)
            lb = (lb -
                  0.5 * sum(omega.alpha .* omega.beta .* diag(etimeseT.mu)) -
                  0.5 * (P * log2pi - sum(psi(omega.alpha) + log(omega.beta)))
            );
            %%%% p(f | b, e, G)
            lb = (lb -
                  0.5 * (f.mu' * f.mu + sum(f.sigma)) +
                  f.mu' * (G.mu' * be.mu(2:P + 1)) +
                  sum(be.mu(1) * f.mu) -
                  0.5 * sum(sum(etimeseT.mu .* GtimesGT.mu)) -
                  sum(G.mu' * etimesb.mu) -
                  0.5 * N * btimesbT.mu - 0.5 * N * log2pi
            );

            %%%% q(lambda)
            lb = (lb +
                  sum(lambda.alpha +
                      log(lambda.beta) +
                      gammaln(lambda.alpha) +
                      (1 - lambda.alpha) .* psi(lambda.alpha)
                   )
            );
            %%%% q(a)
            lb = lb + 0.5 * (D * (log2pi + 1) + logdet(a.sigma));
            %%%% q(G)
            lb = lb + 0.5 * N * (P * (log2pi + 1) + logdet(G.sigma));
            %%%% q(gamma)
            lb = lb + gamma.alpha + log(gamma.beta) + gammaln(gamma.alpha) + (1 - gamma.alpha) * psi(gamma.alpha);
            %%%% q(omega)
            lb = lb + sum(omega.alpha + log(omega.beta) + gammaln(omega.alpha) + (1 - omega.alpha) .* psi(omega.alpha));
            %%%% q(b, e)
            lb = lb + 0.5 * ((P + 1) * (log2pi + 1) + logdet(be.sigma));
            %%%% q(f)
            lb = lb + 0.5 * sum(log2pi + f.sigma) + sum(log(normalization));

            bounds(iter) = lb;
        end
        if mod(iter, 1) == 0
            fprintf(1, '.');
        end
        if mod(iter, 10) == 0
            fprintf(1, ' %5d', iter);
            if parameters.progress==1
                fprintf(1, ' %.4f', bounds(iter));
            end
            fprintf('\n')
        end
    end

    state.lambda = lambda;
    state.a = a;
    state.gamma = gamma;
    state.omega = omega;
    state.be = be;
    if parameters.progress == 1
        state.bounds = bounds;
    end
    state.parameters = parameters;
end

function ld = logdet(Sigma)
    U = chol(Sigma);
    ld = 2 * sum(log(diag(U)));
end

In [8]:
function prediction = bemkl_supervised_classification_variational_test(Km, state)
    N = size(Km, 2);
    P = size(Km, 3);

    prediction.G.mu = zeros(P, N);
    prediction.G.sigma = zeros(P, N);
    for m = 1:P
        prediction.G.mu(m, :) = state.a.mu' * Km(:, :, m);
        prediction.G.sigma(m, :) = state.parameters.sigma_g^2 + diag(Km(:, :, m)' * state.a.sigma * Km(:, :, m));
    end

    prediction.f.mu = [ones(1, N); prediction.G.mu]' * state.be.mu;
    prediction.f.sigma = 1 + diag([ones(1, N); prediction.G.mu]' * state.be.sigma * [ones(1, N); prediction.G.mu]);
    prediction.a.mu = state.a.mu;
    prediction.a.sigma = state.a.sigma;
    prediction.be.mu = state.be.mu;
    prediction.be.sigma = state.be.sigma;

    pos = 1 - normcdf((+state.parameters.margin - prediction.f.mu) ./ prediction.f.sigma);
    neg = normcdf((-state.parameters.margin - prediction.f.mu) ./ prediction.f.sigma);
    prediction.p = pos ./ (pos + neg);
end

In [3]:
Km = load('Km.mat');
Km_train = Km.Km_train;
y_train = double(Km.y_train');
Km_test = Km.Km_test;
y_test = double(Km.y_test');

In [4]:
size(Km_train)
size(y_train)
size(Km_test)
size(y_test)

ans =

   478   478   130

ans =

   478     1

ans =

   478   205   130

ans =

   205     1



In [5]:
typeinfo(Km_train)
typeinfo(y_train)
typeinfo(Km_test)
typeinfo(y_test)

ans = matrix
ans = matrix
ans = matrix
ans = matrix


In [9]:
%initalize the parameters of the algorithm
parameters = struct();

%set the hyperparameters of gamma prior used for sample weights
parameters.alpha_lambda = 1;
parameters.beta_lambda = 1;

%set the hyperparameters of gamma prior used for bias
parameters.alpha_gamma = 1;
parameters.beta_gamma = 1;

%set the hyperparameters of gamma prior used for kernel weights
parameters.alpha_omega = 1;
parameters.beta_omega = 1;

%%% IMPORTANT %%%
%For gamma priors, you can experiment with three different (alpha, beta) values
%(1, 1) => default priors
%(1e-10, 1e+10) => good for obtaining sparsity
%(1e-10, 1e-10) => good for small sample size problems

%set the number of iterations
parameters.iteration = 200;

%set the margin parameter
parameters.margin = 1;

%determine whether you want to calculate and store the lower bound values
parameters.progress = 1;

%set the seed for random number generator used to initalize random variables
parameters.seed = 1606;

%set the standard deviation of intermediate representations
parameters.sigma_g = 0.1;

%initialize the kernels and class labels for training
Ktrain = Km_train; %should be an Ntra x Ntra x P matrix containing similarity values between training samples
ytrain = y_train; %should be an Ntra x 1 matrix containing class labels (contains only -1s and +1s)

%perform training
state = bemkl_supervised_classification_variational_train(Ktrain, ytrain, parameters);

%display the kernel weights
%display(state.be.mu(2:end));

%initialize the kernels for testing
Ktest = Km_test; %should be an Ntra x Ntest x P matrix containing similarity values between training and test samples

%perform prediction
prediction = bemkl_supervised_classification_variational_test(Ktest, state);

%display the predicted probabilities
%display(prediction.p);

..........    10 -1441.1037
..........    20 -1357.7385
..........    30 -1342.0792
..........    40 -1330.9527
..........    50 -1312.2346
..........    60 -1289.9190
..........    70 -1273.8210
..........    80 -1259.3076
..........    90 -1232.9936
..........   100 -1224.3736
..........   110 -1211.8671
..........   120 -1204.9300
..........   130 -1198.3308
..........   140 -1187.7496
..........   150 -1178.5490
..........   160 -1169.2787
..........   170 -1165.1828
..........   180 -1161.7347
..........   190 -1158.1597
..........   200 -1154.0119


In [10]:
save('-6', 'prediction.mat', "prediction")