In [1]:
%pylab inline
np.set_printoptions(precision=6, linewidth=100)

Populating the interactive namespace from numpy and matplotlib


In [2]:
P = 3
b_e_μ = np.ones((1, P + 1))
b_e_μ[0, 0] = 0
b_e_σ = np.eye(P + 1)
b_e_μ

array([[ 0.,  1.,  1.,  1.]])

In [4]:
N = 5
a_μ = np.array([[ 1.601969,  0.329826, -0.117059, -0.314183,  0.218641]])
a_Σ = np.eye(N)
display(a_μ)
a_Σ

array([[ 1.601969,  0.329826, -0.117059, -0.314183,  0.218641]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [5]:
a_sqrd_mu = a_μ.T @ a_μ + a_Σ
a_sqrd_mu

array([[ 3.566305,  0.528371, -0.187525, -0.503311,  0.350256],
       [ 0.528371,  1.108785, -0.038609, -0.103626,  0.072113],
       [-0.187525, -0.038609,  1.013703,  0.036778, -0.025594],
       [-0.503311, -0.103626,  0.036778,  1.098711, -0.068693],
       [ 0.350256,  0.072113, -0.025594, -0.068693,  1.047804]])

In [6]:
λ_β = 1
1 / (1 / λ_β + 0.5 * np.diag(a_sqrd_mu))

array([ 0.359305,  0.643338,  0.663635,  0.64543 ,  0.65621 ])

In [10]:
y = np.random.randn(1, N)
margin = 0.1
G_μ = np.array([
    [-1.31929,  -0.45312,  -0.55603,   1.48597,  -1.83869],
    [-0.80358,  -0.70127,  -0.53890,   2.93264,  -0.96983],
    [-0.10758,  -2.27073,  -0.78157,   1.48413,  -0.35861],
]).T
G_Σ = np.eye(P)
G_sqrd_mu = G_μ.T @ G_μ + N * G_Σ
G_sqrd_mu.T

array([[ 12.843901,   7.818591,   4.470164],
       [  7.818591,  15.968881,   6.800242],
       [  4.470164,   6.800242,  13.109883]])

In [11]:
γ_α = 1
γ_β = 1
γ_α = γ_α + 0.5
γ_β = γ_β
γ_α, γ_β

(1.5, 1)

In [13]:
ω_α, ω_β = 1, 1
ω_α = (ω_α + 0.5) * np.ones(P)
ω_β = ω_β * np.ones(P)
ω_α, ω_β

(array([ 1.5,  1.5,  1.5]), array([ 1.,  1.,  1.]))

In [14]:
b_e_μ = np.ones((1, P + 1))
b_e_μ[0, 0] = 0
b_e_Σ = np.eye(P + 1)
b_sqrd_mu = b_e_μ[0, 0]**2 + b_e_Σ[0, 0]
b_sqrd_mu

1.0

In [16]:
e_μ = np.atleast_2d(b_e_μ[0, 1: P+1])
e_sqrd_mu = e_μ.T @ e_μ + b_e_Σ[1: P+1, 1: P+1]
e_sqrd_mu.T

array([[ 2.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 1.,  1.,  2.]])

In [17]:
b_μ = b_e_μ[0, 0]
etimesb_mu = e_μ * b_μ + b_e_Σ[0, 1: P+1]
etimesb_mu.T

array([[ 0.],
       [ 0.],
       [ 0.]])

In [23]:
Km = np.array([
    np.array([
        [ 0.56838,   1.51626,  -0.20037,   1.45376,  -2.49727],
        [ 1.01879,  -0.40727,  -0.49090,  -1.74470,  -1.28977],
        [-0.15542,   0.53447,  -0.61669,   0.19741,  -1.35775],
        [-0.72485,  -0.51523,  -0.21880,  -0.56786,  -0.78998],
        [-0.67934,   1.33032,   1.57681,  -0.18802,   0.23956],
    ]).T,
    np.array([
        [-0.179153,   0.674168,   1.318130,   0.484322,  -1.617275],
        [ 1.763877,   0.250997,   0.744438,  -0.455527,  -0.428262],
        [ 0.284299,  -0.326718,  -0.981868,  -1.362489,  -0.134497],
        [-0.093904,  -0.223421,  -0.237777,   1.112312,  -0.363701],
        [ 0.491904,   1.638335,   1.226410,   0.882964,  -0.246404],
    ]).T,
    np.array([
        [0.477846,  -0.211240,  -0.271033,  -0.541024,  -1.605032],
        [1.729209,  -0.735072,  -0.930630,  -0.119068,   0.100684],
        [0.410233,  -0.211251,  -0.495780,   0.494715,   0.351183],
        [0.367503,  -0.339801,   0.075237,   0.542799,  -1.512810],
        [0.681412,   1.044796,   1.006449,  -0.343455,   1.513459],
    ])
])

for i in range(3):
    Km[i] = Km[i] @ Km[i].T
Km = Km.reshape(N*P, N)
Km

array([[  2.372055,  -0.166453,  -1.430757,  -0.442533,  -2.112507],
       [ -0.166453,   4.785785,   1.776908,   3.062804,  -3.26119 ],
       [ -1.430757,   1.776908,   3.195641,   0.271219,   2.521425],
       [ -0.442533,   3.062804,   0.271219,   5.554183,  -1.244647],
       [ -2.112507,  -3.26119 ,   2.521425,  -1.244647,  10.424807],
       [  3.474971,   1.055947,   1.42341 ,  -0.947733,  -0.590953],
       [  1.055947,   3.358305,   3.458682,   1.855405,  -1.476299],
       [  1.42341 ,   3.458682,   4.816339,   2.455466,  -2.534247],
       [ -0.947733,   1.855405,   2.455466,   4.315312,  -1.027061],
       [ -0.590953,  -1.476299,  -2.534247,  -1.027061,   3.01007 ],
       [  3.215253,   1.136621,  -0.456287,   2.361439,  -2.411206],
       [  1.136621,   4.420881,   1.302505,   0.598304,  -0.333053],
       [ -0.456287,   1.302505,   0.826788,  -0.077498,  -0.078565],
       [  2.361439,   0.598304,  -0.077498,   2.839409,  -2.504883],
       [ -2.411206,  -0.333053,  -

In [37]:
KmTtimesG_mu = G_μ.T.reshape(1, N * P) @ Km
KmTtimesG_mu.T

array([[ -3.70175 ],
       [ -0.784366],
       [ -4.963807],
       [ 24.163993],
       [-24.6946  ]])

In [26]:
λ_α = (1 + 0.5) * np.ones(N)
λ_β = 1 * np.ones(N)
sigma_g = 0.1

KmKm = np.zeros((N, N))
Km = Km.reshape(P, N, N)
for i in range(P):
    KmKm += Km[i, :, :].T @ Km[i, :, :]
Km = Km.reshape(P*N, N)

a_Σ = np.linalg.solve(
    (np.diag(λ_α * λ_β) + KmKm / sigma_g**2),
    np.eye(N)
)
a_μ = KmTtimesG_mu @ a_Σ / sigma_g**2
a_sqrd_μ = a_μ.T @ a_μ + a_Σ

display(a_μ.T)
display(a_Σ.T)
a_sqrd_μ.T

array([[-0.372648],
       [-0.503973],
       [ 0.08624 ],
       [ 0.447222],
       [-0.304406]])

array([[  3.393376e-04,   2.703616e-05,  -4.548174e-05,   3.773875e-05,   1.407879e-04],
       [  2.703616e-05,   3.771051e-04,  -2.219671e-04,  -9.674394e-05,   1.313759e-04],
       [ -4.548174e-05,  -2.219671e-04,   3.174410e-04,  -4.732261e-05,  -1.293423e-04],
       [  3.773875e-05,  -9.674394e-05,  -4.732261e-05,   2.356750e-04,   6.150390e-05],
       [  1.407879e-04,   1.313759e-04,  -1.293423e-04,   6.150390e-05,   1.797699e-04]])

array([[ 0.139206,  0.187832, -0.032183, -0.166619,  0.113577],
       [ 0.187832,  0.254366, -0.043685, -0.225485,  0.153544],
       [-0.032183, -0.043685,  0.007755,  0.038521, -0.026381],
       [-0.166619, -0.225485,  0.038521,  0.200243, -0.136075],
       [ 0.113577,  0.153544, -0.026381, -0.136075,  0.092843]])

In [53]:
f_μ = np.array([[-0.311384,  0.184717, -1.016264,  0.147183,  0.877273]])
f_σ = np.ones(N)

G_Σ = np.linalg.solve(
    (np.eye(P) / sigma_g**2 + e_sqrd_mu),
    np.eye(P)
)
G_μ = ((a_μ @ Km.T).reshape(P, N).T / sigma_g**2 +
       np.outer(f_μ, b_e_μ[0, 1: P + 1]) -
       etimesb_mu) @ G_Σ
G_sqrd_μ = G_μ.T @ G_μ + N * G_Σ
KmTtimesG_μ = G_μ.T.reshape(N * P) @ Km

display(G_μ.T)
display(G_Σ.T)
display(G_sqrd_μ.T)
display(KmTtimesG_μ.T)

array([[ -4.532580e-01,   1.898999e-01,  -7.245836e-01,   1.453835e+00,  -1.031339e+00],
       [ -1.908721e+00,  -4.778065e-01,   1.246592e-02,   1.815065e+00,  -5.839589e-01],
       [  2.393523e-04,  -2.123090e+00,  -4.204656e-01,   7.969915e-01,  -1.520442e+00]])

array([[  9.805788e-03,  -9.520183e-05,  -9.520183e-05],
       [ -9.520183e-05,   9.805788e-03,  -9.520183e-05],
       [ -9.520183e-05,  -9.520183e-05,   9.805788e-03]])

array([[ 3.992851,  4.005964,  2.627688],
       [ 4.005964,  7.55617 ,  3.342719],
       [ 2.627688,  3.342719,  7.680268]])

array([ -3.70175 ,  -0.784366,  -4.963807,  24.163993, -24.6946  ])

In [54]:
γ_β = 1 / (1 / γ_β + 0.5 * b_sqrd_mu)
γ_α, γ_β

(1.5, 0.66666666666666663)

In [55]:
ω_β = 1 / (1 / ω_β + 0.5 * np.diag(e_sqrd_mu))
ω_α, ω_β

(array([ 1.5,  1.5,  1.5]), array([ 0.5,  0.5,  0.5]))

In [92]:
b_e_Σ = np.linalg.solve(
    np.r_['1,2',
          np.r_['1,2', [γ_α * γ_β + N], G_μ.sum(axis=0)].T,
          np.r_['0,2', G_μ.sum(axis=0), np.diag(ω_α * ω_β) + G_sqrd_μ]],
    np.eye(P + 1)
)
b_e_μ = (f_μ @ np.r_['1,2', np.ones((N, 1)), G_μ]) @ b_e_Σ
e_μ = np.atleast_2d(b_e_μ[0, 1: P + 1])
b_μ = b_e_μ[0, 0]
b_sqrd_μ = b_μ**2 + b_e_Σ[0, 0]
e_sqrd_μ = e_μ.T @ e_μ + b_e_Σ[1: P + 1, 1: P + 1]
etimesb_μ = e_μ * b_μ + b_e_Σ[0, 1: P + 1]

display(b_e_μ.T)
display(b_e_Σ.T)
display(b_sqrd_μ)
display(e_sqrd_μ)
etimesb_μ

array([[-0.135541],
       [ 0.126941],
       [ 0.051734],
       [-0.25275 ]])

array([[ 0.213937, -0.031152,  0.008558,  0.089218],
       [-0.031152,  0.379734, -0.160557, -0.066771],
       [ 0.008558, -0.160557,  0.211238, -0.030397],
       [ 0.089218, -0.066771, -0.030397,  0.186058]])

0.23230814495412966

array([[ 0.395848, -0.15399 , -0.098855],
       [-0.15399 ,  0.213914, -0.043473],
       [-0.098855, -0.043473,  0.24994 ]])

array([[-0.048358,  0.001546,  0.123476]])

In [121]:
from scipy.stats import norm as sp_norm

y = np.array([0.83460, 0.75760, -0.58986, 1.18739, -1.98762])
lower_bound = -1e40 * np.ones(N)
lower_bound[y > 0] =  margin
upper_bound = 1e40 * np.ones(N)
upper_bound[y < 0] = -margin

output = b_e_μ @ np.r_['1,2', np.ones((N, 1)), G_μ].T
alpha_norm = lower_bound - output
beta_norm = upper_bound - output
normalization = sp_norm.cdf(beta_norm) - sp_norm.cdf(alpha_norm)
normalization[normalization == 0] = 1
f_μ = (
    output +
    (sp_norm.pdf(alpha_norm) - sp_norm.pdf(beta_norm)) /
    normalization
)
f_Σ = (
    1 +
    (alpha_norm * sp_norm.pdf(alpha_norm) -
     beta_norm * sp_norm.pdf(beta_norm)) / normalization -
    (sp_norm.pdf(alpha_norm) -
     sp_norm.pdf(beta_norm))**2 / normalization**2
)
display(output.T)
print()
display(alpha_norm.T)
print()
display(beta_norm.T)
print()
display(normalization.T)
print()
display(f_μ.T)
print()
f_Σ.T

array([[-0.291883],
       [ 0.400458],
       [-0.120602],
       [-0.058529],
       [ 0.087622]])

array([[  1.291883e+00],
       [  5.995419e-01],
       [ -1.000000e+40],
       [  1.058529e+00],
       [ -1.000000e+40]])

array([[  1.000000e+40],
       [  1.000000e+40],
       [ -8.793977e-01],
       [  1.000000e+40],
       [ -1.087622e+00]])

array([[ 0.098199],
       [ 0.274406],
       [ 0.189593],
       [ 0.144907],
       [ 0.138381]])

array([[ 1.471689],
       [ 1.615142],
       [-1.550021],
       [ 1.51368 ],
       [-1.50813 ]])

array([[ 0.168141],
       [ 0.252798],
       [ 0.21379 ],
       [ 0.192388],
       [ 0.18915 ]])

In [103]:
b_e_μ @ np.r_['1,2', np.ones((N, 1)), G_μ].T

array([[-0.291883,  0.400458, -0.120602, -0.058529,  0.087622]])

In [39]:
from scipy.stats import norm as sp_norm
Km = np.array([
    np.array([
        [ 0.56838,   1.51626,  -0.20037,   1.45376,  -2.49727],
        [ 1.01879,  -0.40727,  -0.49090,  -1.74470,  -1.28977],
        [-0.15542,   0.53447,  -0.61669,   0.19741,  -1.35775],
        [-0.72485,  -0.51523,  -0.21880,  -0.56786,  -0.78998],
        [-0.67934,   1.33032,   1.57681,  -0.18802,   0.23956],
    ]).T,
    np.array([
        [-0.179153,   0.674168,   1.318130,   0.484322,  -1.617275],
        [ 1.763877,   0.250997,   0.744438,  -0.455527,  -0.428262],
        [ 0.284299,  -0.326718,  -0.981868,  -1.362489,  -0.134497],
        [-0.093904,  -0.223421,  -0.237777,   1.112312,  -0.363701],
        [ 0.491904,   1.638335,   1.226410,   0.882964,  -0.246404],
    ]).T,
    np.array([
        [0.477846,  -0.211240,  -0.271033,  -0.541024,  -1.605032],
        [1.729209,  -0.735072,  -0.930630,  -0.119068,   0.100684],
        [0.410233,  -0.211251,  -0.495780,   0.494715,   0.351183],
        [0.367503,  -0.339801,   0.075237,   0.542799,  -1.512810],
        [0.681412,   1.044796,   1.006449,  -0.343455,   1.513459],
    ])
])

P, N, _ = Km.shape

a_mu = np.array([-0.372648, -0.503973, 0.086240, 0.447222, -0.304406])
a_sigma = np.array([
      [ 3.3934e-04,   2.7036e-05,  -4.5482e-05,   3.7739e-05,   1.4079e-04],
      [ 2.7036e-05,   3.7711e-04,  -2.2197e-04,  -9.6744e-05,   1.3138e-04],
      [-4.5482e-05,  -2.2197e-04,   3.1744e-04,  -4.7323e-05,  -1.2934e-04],
      [ 3.7739e-05,  -9.6744e-05,  -4.7323e-05,   2.3568e-04,   6.1504e-05],
      [ 1.4079e-04,   1.3138e-04,  -1.2934e-04,   6.1504e-05,   1.7977e-04],
]).T
b_e_mu = np.array([-0.135540, 0.126941, 0.051734, -0.252750])
b_e_sigma = np.array([
      [ 0.2139369,  -0.0311523,   0.0085580,   0.0892182],
      [-0.0311523,   0.3797341,  -0.1605567,  -0.0667706],
      [ 0.0085580,  -0.1605567,   0.2112376,  -0.0303974],
      [ 0.0892182,  -0.0667706,  -0.0303974,   0.1860578],
]).T
sigma_g = 0.1
margin = 1

for i in range(3):
    Km[i] = Km[i] @ Km[i].T

G_mu = np.zeros((N, P))
G_sigma = np.zeros((N, P))
for i in range(P):
    G_mu[:, i] = Km[i, :, :].T @ a_mu
    G_sigma[:, i] = (
        sigma_g**2 +
        np.diag(Km[i, :, :] @ a_sigma.T @ Km[i, :, :].T)
    )

G_mu_ext = np.r_['1,2', np.ones((N, 1)), G_mu]
f_mu = G_mu_ext @ b_e_mu
f_sigma = 1 + np.diag(G_mu_ext @ b_e_sigma @ G_mu_ext.T)
pos = 1 - sp_norm.cdf((margin - f_mu) / f_sigma)
neg = sp_norm.cdf((-margin - f_mu) / f_sigma)
p = pos / (pos + neg)
p

array([ 0.404743,  0.635032,  0.443307,  0.481038,  0.540082])

In [36]:
(-margin - f_mu) / f_sigma

array([-0.39499 , -0.801165, -0.636074, -0.503285, -0.742019])