In [1]:
P = 3;
be.mu = [0; ones(P, 1)];
be.sigma = eye(P + 1, P + 1);
be.mu

ans =

   0
   1
   1
   1



In [4]:
N = 5;
a.mu = [1.601969;  0.329826; -0.117059; -0.314183;  0.218641];
a.sigma = eye(N, N);
a

a =

  scalar structure containing the fields:

    mu =

       1.60197
       0.32983
      -0.11706
      -0.31418
       0.21864

    sigma =

Diagonal Matrix

       1   0   0   0   0
       0   1   0   0   0
       0   0   1   0   0
       0   0   0   1   0
       0   0   0   0   1




In [5]:
atimesaT.mu = a.mu * a.mu' + a.sigma

atimesaT =

  scalar structure containing the fields:

    mu =

       3.566305   0.528371  -0.187525  -0.503311   0.350256
       0.528371   1.108785  -0.038609  -0.103626   0.072113
      -0.187525  -0.038609   1.013703   0.036778  -0.025594
      -0.503311  -0.103626   0.036778   1.098711  -0.068693
       0.350256   0.072113  -0.025594  -0.068693   1.047804




In [12]:
parameters.margin = 0.1;
y = randn(N, 1);
%G.mu = (abs(randn(P, N)) + parameters.margin) .* sign(repmat(y', P, 1))
G.mu = [
      -1.31929  -0.45312  -0.55603   1.48597  -1.83869;
      -0.80358  -0.70127  -0.53890   2.93264  -0.96983;
      -0.10758  -2.27073  -0.78157   1.48413  -0.35861;
];
G.sigma = eye(P, P);
GtimesGT.mu = G.mu * G.mu' + N * G.sigma

GtimesGT =

  scalar structure containing the fields:

    mu =

       12.8439    7.8186    4.4702
        7.8186   15.9689    6.8002
        4.4702    6.8002   13.1099




In [13]:
parameters.alpha_gamma = 1;
parameters.beta_gamma = 1;
gamma.alpha = (parameters.alpha_gamma + 0.5);
gamma.beta = parameters.beta_gamma

gamma =

  scalar structure containing the fields:

    alpha =  1.5000
    beta =  1



In [14]:
parameters.alpha_omega = 1;
parameters.beta_omega = 1;
omega.alpha = (parameters.alpha_omega + 0.5) * ones(P, 1);
omega.beta = parameters.beta_omega * ones(P, 1)

omega =

  scalar structure containing the fields:

    alpha =

       1.5000
       1.5000
       1.5000

    beta =

       1
       1
       1




In [16]:
be.mu = [0; ones(P, 1)];
be.sigma = eye(P + 1, P + 1);
btimesbT.mu = be.mu(1)^2 + be.sigma(1, 1)

btimesbT =

  scalar structure containing the fields:

    mu =  1



In [17]:
etimeseT.mu = be.mu(2:P + 1) * be.mu(2:P + 1)' + be.sigma(2:P + 1, 2:P + 1)

etimeseT =

  scalar structure containing the fields:

    mu =

       2   1   1
       1   2   1
       1   1   2




In [18]:
etimesb.mu = be.mu(2:P + 1) * be.mu(1) + be.sigma(2:P + 1, 1)

etimesb =

  scalar structure containing the fields:

    mu =

       0
       0
       0




In [1]:
Km = [
    2.372055,  -0.166453,  -1.430757,  -0.442533,  -2.112507;
   -0.166453,   4.785785,   1.776908,   3.062804,  -3.26119 ;
   -1.430757,   1.776908,   3.195641,   0.271219,   2.521425;
   -0.442533,   3.062804,   0.271219,   5.554183,  -1.244647;
   -2.112507,  -3.26119 ,   2.521425,  -1.244647,  10.424807;
    3.474971,   1.055947,   1.42341 ,  -0.947733,  -0.590953;
    1.055947,   3.358305,   3.458682,   1.855405,  -1.476299;
    1.42341 ,   3.458682,   4.816339,   2.455466,  -2.534247;
   -0.947733,   1.855405,   2.455466,   4.315312,  -1.027061;
   -0.590953,  -1.476299,  -2.534247,  -1.027061,   3.01007 ;
    3.215253,   1.136621,  -0.456287,   2.361439,  -2.411206;
    1.136621,   4.420881,   1.302505,   0.598304,  -0.333053;
   -0.456287,   1.302505,   0.826788,  -0.077498,  -0.078565;
    2.361439,   0.598304,  -0.077498,   2.839409,  -2.504883;
   -2.411206,  -0.333053,  -0.078565,  -2.504883,   4.97738
]';
Km'

ans =

    2.372055   -0.166453   -1.430757   -0.442533   -2.112507
   -0.166453    4.785785    1.776908    3.062804   -3.261190
   -1.430757    1.776908    3.195641    0.271219    2.521425
   -0.442533    3.062804    0.271219    5.554183   -1.244647
   -2.112507   -3.261190    2.521425   -1.244647   10.424807
    3.474971    1.055947    1.423410   -0.947733   -0.590953
    1.055947    3.358305    3.458682    1.855405   -1.476299
    1.423410    3.458682    4.816339    2.455466   -2.534247
   -0.947733    1.855405    2.455466    4.315312   -1.027061
   -0.590953   -1.476299   -2.534247   -1.027061    3.010070
    3.215253    1.136621   -0.456287    2.361439   -2.411206
    1.136621    4.420881    1.302505    0.598304   -0.333053
   -0.456287    1.302505    0.826788   -0.077498   -0.078565
    2.361439    0.598304   -0.077498    2.839409   -2.504883
   -2.411206   -0.333053   -0.078565   -2.504883    4.977380



In [28]:
KmtimesGT.mu = Km * reshape(G.mu', N * P, 1)

KmtimesGT =

  scalar structure containing the fields:

    mu =

       -3.73891
       -0.75541
       -5.07515
       24.93586
      -25.63559




In [30]:
parameters.alpha_lambda = 1;
parameters.beta_lambda = 1;
lambda.alpha = (parameters.alpha_lambda + 0.5) * ones(N, 1);
lambda.beta = parameters.beta_lambda * ones(N, 1);
sigma_g = 0.1;

Km = reshape(Km, [N, N, P]);
KmKm = zeros(N, N);
for m = 1:P
    KmKm = KmKm + Km(:, :, m) * Km(:, :, m)';
end
Km = reshape(Km, [N, N * P]);

a.sigma = (diag(lambda.alpha .* lambda.beta) + KmKm / sigma_g^2) \ eye(N, N);
a.mu = a.sigma * KmtimesGT.mu / sigma_g^2
atimesaT.mu = a.mu * a.mu' + a.sigma

a =

  scalar structure containing the fields:

    mu =

      -0.372648
      -0.503973
       0.086240
       0.447222
      -0.304406

    sigma =

       3.3934e-04   2.7036e-05  -4.5482e-05   3.7739e-05   1.4079e-04
       2.7036e-05   3.7711e-04  -2.2197e-04  -9.6744e-05   1.3138e-04
      -4.5482e-05  -2.2197e-04   3.1744e-04  -4.7323e-05  -1.2934e-04
       3.7739e-05  -9.6744e-05  -4.7323e-05   2.3568e-04   6.1504e-05
       1.4079e-04   1.3138e-04  -1.2934e-04   6.1504e-05   1.7977e-04


atimesaT =

  scalar structure containing the fields:

    mu =

       0.1392059   0.1878316  -0.0321828  -0.1666187   0.1135770
       0.1878316   0.2543658  -0.0436847  -0.2254846   0.1535436
      -0.0321828  -0.0436847   0.0077548   0.0385212  -0.0263814
      -0.1666187  -0.2254846   0.0385212   0.2002433  -0.1360754
       0.1135770   0.1535436  -0.0263814  -0.1360754   0.0928426




In [32]:
parameters.margin = 1;
f.mu = [-0.311384;  0.184717; -1.016264;  0.147183;  0.877273];
f.sigma = ones(N, 1);

G.sigma = (eye(P, P) / sigma_g^2 + etimeseT.mu) \ eye(P, P);
G.mu = G.sigma * (reshape(a.mu' * Km, [N, P])' / sigma_g^2 + be.mu(2:P + 1) * f.mu' - repmat(etimesb.mu, 1, N))

GtimesGT.mu = G.mu * G.mu' + N * G.sigma
KmtimesGT.mu = Km * reshape(G.mu', N * P, 1)

G =

  scalar structure containing the fields:

    mu =

      -4.5326e-01   1.8990e-01  -7.2458e-01   1.4538e+00  -1.0313e+00
      -1.9087e+00  -4.7781e-01   1.2466e-02   1.8151e+00  -5.8396e-01
       2.3922e-04  -2.1231e+00  -4.2047e-01   7.9699e-01  -1.5204e+00

    sigma =

       9.8058e-03  -9.5202e-05  -9.5202e-05
      -9.5202e-05   9.8058e-03  -9.5202e-05
      -9.5202e-05  -9.5202e-05   9.8058e-03


GtimesGT =

  scalar structure containing the fields:

    mu =

       3.9928   4.0060   2.6277
       4.0060   7.5562   3.3427
       2.6277   3.3427   7.6803


KmtimesGT =

  scalar structure containing the fields:

    mu =

       -3.70175
       -0.78437
       -4.96381
       24.16399
      -24.69460




In [33]:
gamma.beta = 1 / (1 / parameters.beta_gamma + 0.5 * btimesbT.mu)

gamma =

  scalar structure containing the fields:

    alpha =  1.5000
    beta =  0.66667



In [34]:
omega.beta = 1 ./ (1 / parameters.beta_omega + 0.5 * diag(etimeseT.mu))

omega =

  scalar structure containing the fields:

    alpha =

       1.5000
       1.5000
       1.5000

    beta =

       0.50000
       0.50000
       0.50000




In [37]:
be.sigma = [gamma.alpha * gamma.beta + N, sum(G.mu, 2)'; sum(G.mu, 2), diag(omega.alpha .* omega.beta) + GtimesGT.mu] \ eye(P + 1, P + 1);
be.mu = be.sigma * ([ones(1, N); G.mu] * f.mu)
btimesbT.mu = be.mu(1)^2 + be.sigma(1, 1)
etimeseT.mu = be.mu(2:P + 1) * be.mu(2:P + 1)' + be.sigma(2:P + 1, 2:P + 1)
etimesb.mu = be.mu(2:P + 1) * be.mu(1) + be.sigma(2:P + 1, 1)

be =

  scalar structure containing the fields:

    mu =

      -0.135540
       0.126941
       0.051734
      -0.252750

    sigma =

       0.2139369  -0.0311523   0.0085580   0.0892182
      -0.0311523   0.3797341  -0.1605567  -0.0667706
       0.0085580  -0.1605567   0.2112376  -0.0303974
       0.0892182  -0.0667706  -0.0303974   0.1860578


btimesbT =

  scalar structure containing the fields:

    mu =  0.23231

etimeseT =

  scalar structure containing the fields:

    mu =

       0.395848  -0.153990  -0.098855
      -0.153990   0.213914  -0.043473
      -0.098855  -0.043473   0.249940


etimesb =

  scalar structure containing the fields:

    mu =

      -0.0483579
       0.0015460
       0.1234761




In [42]:
y

y =

   0.83460
   0.75760
  -0.58986
   1.18739
  -1.98762



In [48]:
lower_bound = -1e40 * ones(N, 1);
lower_bound(y > 0) = +parameters.margin;
upper_bound = +1e40 * ones(N, 1);
upper_bound(y < 0) = -parameters.margin;

output = [ones(1, N); G.mu]' * be.mu
alpha_norm = lower_bound - output
beta_norm = upper_bound - output
normalization = normcdf(beta_norm) - normcdf(alpha_norm);
normalization(normalization == 0) = 1
f.mu = output + (normpdf(alpha_norm) - normpdf(beta_norm)) ./ normalization;
f.sigma = 1 + (alpha_norm .* normpdf(alpha_norm) - beta_norm .* normpdf(beta_norm)) ./ normalization - (normpdf(alpha_norm) - normpdf(beta_norm)).^2 ./ normalization.^2

output =

  -0.291883
   0.400458
  -0.120602
  -0.058529
   0.087622

alpha_norm =

   1.2919e+00
   5.9954e-01
  -1.0000e+40
   1.0585e+00
  -1.0000e+40

beta_norm =

   1.0000e+40
   1.0000e+40
  -8.7940e-01
   1.0000e+40
  -1.0876e+00

normalization =

   0.098199
   0.274406
   0.189593
   0.144907
   0.138381

f =

  scalar structure containing the fields:

    mu =

       1.4717
       1.6151
      -1.5500
       1.5137
      -1.5081

    sigma =

       0.16814
       0.25280
       0.21379
       0.19239
       0.18915




In [3]:
Km = [
    2.372055,  -0.166453,  -1.430757,  -0.442533,  -2.112507;
   -0.166453,   4.785785,   1.776908,   3.062804,  -3.26119 ;
   -1.430757,   1.776908,   3.195641,   0.271219,   2.521425;
   -0.442533,   3.062804,   0.271219,   5.554183,  -1.244647;
   -2.112507,  -3.26119 ,   2.521425,  -1.244647,  10.424807;
    3.474971,   1.055947,   1.42341 ,  -0.947733,  -0.590953;
    1.055947,   3.358305,   3.458682,   1.855405,  -1.476299;
    1.42341 ,   3.458682,   4.816339,   2.455466,  -2.534247;
   -0.947733,   1.855405,   2.455466,   4.315312,  -1.027061;
   -0.590953,  -1.476299,  -2.534247,  -1.027061,   3.01007 ;
    3.215253,   1.136621,  -0.456287,   2.361439,  -2.411206;
    1.136621,   4.420881,   1.302505,   0.598304,  -0.333053;
   -0.456287,   1.302505,   0.826788,  -0.077498,  -0.078565;
    2.361439,   0.598304,  -0.077498,   2.839409,  -2.504883;
   -2.411206,  -0.333053,  -0.078565,  -2.504883,   4.97738
]';

N = 5;
P = 3;
Km = reshape(Km, N, N, P);
N = size(Km, 2);
P = size(Km, 3);

state.a.mu = [-0.372648; -0.503973; 0.086240; 0.447222; -0.304406];
state.a.sigma =[
       3.3934e-04   2.7036e-05  -4.5482e-05   3.7739e-05   1.4079e-04;
       2.7036e-05   3.7711e-04  -2.2197e-04  -9.6744e-05   1.3138e-04;
      -4.5482e-05  -2.2197e-04   3.1744e-04  -4.7323e-05  -1.2934e-04;
       3.7739e-05  -9.6744e-05  -4.7323e-05   2.3568e-04   6.1504e-05;
       1.4079e-04   1.3138e-04  -1.2934e-04   6.1504e-05   1.7977e-04;
];
state.be.mu = [-0.135540; 0.126941; 0.051734; -0.252750];
state.be.sigma =[
       0.2139369  -0.0311523   0.0085580   0.0892182;
      -0.0311523   0.3797341  -0.1605567  -0.0667706;
       0.0085580  -0.1605567   0.2112376  -0.0303974;
       0.0892182  -0.0667706  -0.0303974   0.1860578;
];
state.parameters.sigma_g = 0.1;
state.parameters.margin = 1;

prediction.G.mu = zeros(P, N);
prediction.G.sigma = zeros(P, N);
for m = 1:P
    prediction.G.mu(m, :) = state.a.mu' * Km(:, :, m);
    prediction.G.sigma(m, :) = state.parameters.sigma_g^2 + diag(Km(:, :, m)' * state.a.sigma * Km(:, :, m));
end

prediction.G

prediction.f.mu = [ones(1, N); prediction.G.mu]' * state.be.mu;
prediction.f.sigma = 1 + diag([ones(1, N); prediction.G.mu]' * state.be.sigma * [ones(1, N); prediction.G.mu])

pos = 1 - normcdf((+state.parameters.margin - prediction.f.mu) ./ prediction.f.sigma)
neg = normcdf((-state.parameters.margin - prediction.f.mu) ./ prediction.f.sigma)
prediction.p = pos ./ (pos + neg)

ans =

  scalar structure containing the fields:

    mu =

      -0.478293   0.165842  -0.732995   1.507559  -1.081786
      -1.948312  -0.508543   0.011426   1.872402  -0.629929
      -0.020261  -2.170278  -0.425834   0.844150  -1.575778

    sigma =

       0.011461   0.012913   0.012002   0.015516   0.018133
       0.014134   0.011912   0.013960   0.013209   0.012537
       0.013250   0.015092   0.010483   0.012385   0.012992


prediction =

  scalar structure containing the fields:

    G =

      scalar structure containing the fields:

        mu =

          -0.478293   0.165842  -0.732995   1.507559  -1.081786
          -1.948312  -0.508543   0.011426   1.872402  -0.629929
          -0.020261  -2.170278  -0.425834   0.844150  -1.575778

        sigma =

           0.011461   0.012913   0.012002   0.015516   0.018133
           0.014134   0.011912   0.013960   0.013209   0.012537
           0.013250   0.015092   0.010483   0.012385   0.012992


    f =

      scalar structure c

In [8]:
(-state.parameters.margin - prediction.f.mu)./prediction.f.sigma

ans =

  -0.39499
  -0.80117
  -0.63607
  -0.50329
  -0.74202

